"""
Steering assistant MCP server.
Reads from data/synthetic.json (generated by generate_data.py).
Run: poetry run mcp dev server.py
"""

import json
from pathlib import Path
from typing import Optional

from mcp.server.fastmcp import FastMCP

DATA_FILE = Path(__file__).parent / "data" / "synthetic.json"

mcp = FastMCP("steering-mcp")


def load_data() -> list[dict]:
    return json.loads(DATA_FILE.read_text())


@mcp.tool()
def get_steering_snapshot(week: str) -> list[dict]:
    """
    Returns all MMM rows for the given week, sorted by absolute spend delta descending.
    Call this at the start of every session to load the full context.
    week: ISO week string, e.g. '2026-W22'
    """
    data = load_data()
    rows = [r for r in data if r["week"] == week]
    rows.sort(key=lambda r: abs(r["spend_delta"]), reverse=True)
    return rows


@mcp.tool()
def get_country_channel(country: Optional[str] = None, channel: Optional[str] = None) -> list[dict]:
    """
    Returns rows filtered by country, channel, or both.
    country: ISO 2-letter country code, e.g. 'DE'
    channel: channel name, e.g. 'paid_search'
    """
    rows = load_data()
    if country:
        rows = [r for r in rows if r["country"] == country.upper()]
    if channel:
        rows = [r for r in rows if r["channel"] == channel.lower()]
    return rows


class SpendChange:
    def __init__(self, country: str, channel: str, new_spend: float):
        self.country = country
        self.channel = channel
        self.new_spend = new_spend


@mcp.tool()
def run_scenario(changes: list[dict]) -> dict:
    """
    Simulates a budget reallocation. Returns projected incremental revenue impact and a summary.
    changes: list of {country, channel, new_spend} dicts
    """
    data = load_data()
    index = {(r["country"], r["channel"]): r for r in data}

    enriched_changes = []
    total_incremental_revenue = 0
    total_spend_delta = 0

    for change in changes:
        key = (change["country"].upper(), change["channel"].lower())
        row = index.get(key)
        if row is None:
            enriched_changes.append({**change, "error": "row not found"})
            continue

        current_spend = row["current_spend"]
        recommended_spend = row["recommended_spend"]
        new_spend = change["new_spend"]
        roi = row["roi"]
        spend_diff = new_spend - current_spend

        if spend_diff > 0:
            up_to_recommended = min(spend_diff, max(0, recommended_spend - current_spend))
            excess = max(0, spend_diff - up_to_recommended)
            incremental_rev = (up_to_recommended * roi) + (excess * roi * 0.6)
        else:
            incremental_rev = spend_diff * roi * 0.9  # negative

        incremental_rev = round(incremental_rev)
        total_incremental_revenue += incremental_rev
        total_spend_delta += spend_diff

        saturation_after = row["saturation_pct"]
        if new_spend > recommended_spend:
            overage_pct = (new_spend - recommended_spend) / recommended_spend
            saturation_after = min(100, round(row["saturation_pct"] + overage_pct * 15))

        enriched_changes.append({
            "country": change["country"].upper(),
            "channel": change["channel"].lower(),
            "current_spend": current_spend,
            "new_spend": new_spend,
            "spend_delta": spend_diff,
            "incremental_revenue": incremental_rev,
            "roi": roi,
            "saturation_pct_after": saturation_after,
        })

    increases = [c for c in enriched_changes if c.get("spend_delta", 0) > 0]
    decreases = [c for c in enriched_changes if c.get("spend_delta", 0) < 0]

    summary_parts = []
    if decreases:
        cut_str = ", ".join(
            f"{c['country']} {c['channel']} (€{abs(c['spend_delta']):,.0f})"
            for c in decreases
        )
        summary_parts.append(f"Cutting {cut_str}")
    if increases:
        add_str = ", ".join(
            f"{c['country']} {c['channel']} (€{c['spend_delta']:,.0f})"
            for c in increases
        )
        summary_parts.append(f"adding to {add_str}")

    summary = ". ".join(summary_parts)
    if total_incremental_revenue > 0:
        summary += f". Projects +€{total_incremental_revenue:,.0f} incremental revenue."
    else:
        summary += f". Projects €{total_incremental_revenue:,.0f} revenue impact."

    over_sat = [c for c in enriched_changes if c.get("saturation_pct_after", 0) > 90]
    if over_sat:
        flags = ", ".join(f"{c['country']} {c['channel']}" for c in over_sat)
        summary += f" Warning: {flags} would exceed 90% saturation at new spend level."
    else:
        under = [c for c in increases if c.get("saturation_pct_after", 0) <= 85]
        if under:
            summary += " All increased channels remain below saturation curve."

    return {
        "changes": enriched_changes,
        "total_incremental_revenue": total_incremental_revenue,
        "total_spend_delta": round(total_spend_delta),
        "summary": summary,
    }


@mcp.tool()
def get_saturation_flags(threshold: int = 80) -> list[dict]:
    """
    Returns all rows where action is 'decrease' or 'watch', sorted by saturation_pct descending.
    threshold: minimum saturation_pct to include (default 80)
    """
    data = load_data()
    rows = [
        r for r in data
        if r["action"] in ("decrease", "watch") and r["saturation_pct"] >= threshold
    ]
    rows.sort(key=lambda r: r["saturation_pct"], reverse=True)
    return [
        {
            "country": r["country"],
            "channel": r["channel"],
            "action": r["action"],
            "saturation_pct": r["saturation_pct"],
            "roi": r["roi"],
            "spend_delta": r["spend_delta"],
            "notes": r["notes"],
        }
        for r in rows
    ]

if __name__ == "__main__":
    mcp.run()
